services:
  - type: web
    name: phishgame-backend
    runtime: python
    buildCommand: pip install -r phishgame/requirements.txt  # Adjusted path
    startCommand: gunicorn --workers 3 --bind 0.0.0.0:$PORT phishgame.server:app  # Adjusted path
    envVars:
      - key: FLASK_APP
        value: phishgame/server.py  # Adjusted path
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
    disk:
      name: static-files
      mountPath: /opt/render/project/static
    routes:
      - source: /api(.*)
        destination: /api$1
      - source: /(.*)
        destination: /

disks:
  - name: static-files
    mountPath: /opt/render/project/static
    sizeGB: 1